language: php

matrix:
  include:
    - php: '7.4'
      env: LARAVEL='^8.0' ORCHESTRA="6.*.*" COMPOSER_FLAGS='--prefer-stable'

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

install:
  - composer require "illuminate/auth:${LARAVEL}" --no-interaction --no-update
  - composer require "illuminate/container:${LARAVEL}" --no-interaction --no-update
  - composer require "illuminate/contracts:${LARAVEL}" --no-interaction --no-update
  - composer require "illuminate/database:${LARAVEL}" --no-interaction --no-update
  - composer require "orchestra/testbench:${ORCHESTRA}" --no-interaction --no-update

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
