name: tests

on:
  push:
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'

jobs:
    run-tests:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest]
                php: [8.1, 8.2]
                laravel: [9.*, 8.*]
                stability: [prefer-stable]
                include:
                    - laravel: 8.*
                      testbench: 6.*
                    - laravel: 9.*
                      testbench: 7.*
                    - laravel: 10.*
                      testbench: 8.*
        name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }} - ${{ matrix.os }}

        steps:

            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, exif
                  coverage: none

            - name: Setup problem matchers
              run: |
                echo "::add-matcher::${{ runner.tool_cache }}/php.json"
                echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

            - name: Install dependencies
              run: |
                  composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
                  composer update --${{ matrix.stability }} --prefer-dist --no-interaction --no-suggest

            - name: Execute tests
              run: vendor/bin/phpunit
